[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable", 
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start:prod"
